Update example and reviewdog.yml
reviewdog/action-depup pull request #30
Opened 2021-02-11 11:17 UTC by tsuyoshicho

## example update

Use github.workflow , github.job for Pull-request message.
This copy to use genericaly.

## depup.yml update

Update above change.

2021-02-11 14:30 UTC, haya14busa requested changes
How about using `steps.depup.outputs.repo` instead of `github.job`?

2021-02-11 23:33 UTC, tsuyoshicho commented
> How about using `steps.depup.outputs.repo` instead of `github.job`?

I think to keep the characteristics of the old format.
update it.

2021-02-12 11:21 UTC, haya14busa commented on .github/workflows/depup.yml
> -            Update redpen to [${{ steps.depup.outputs.latest }}](https://github.com/redpen-cc/redpen/releases/tag/redpen-${{ steps.depup.outputs.latest }})
`redpen-` prefix should be required.

2021-02-12 15:15 UTC, tsuyoshicho commented on .github/workflows/depup.yml
> -            Update redpen to [${{ steps.depup.outputs.latest }}](https://github.com/redpen-cc/redpen/releases/tag/redpen-${{ steps.depup.outputs.latest }})
oops... I check link, and fix it.

2021-02-13 00:10 UTC, tsuyoshicho commented on .github/workflows/depup.yml
> -            Update redpen to [${{ steps.depup.outputs.latest }}](https://github.com/redpen-cc/redpen/releases/tag/redpen-${{ steps.depup.outputs.latest }})
fixed

2021-02-13 09:49 UTC, haya14busa approved these changes
:+1:

2021-02-13 09:49 UTC, merged